### ISSUE TITLE
Can't install Aruba Ansible modules with Ansible 2.10+

### ISSUE THREAD

**Issue by MauvaisJoueur** [aruba/aruba-ansible-modules#121]
Can't install Aruba Ansible modules, as described in the official documentation, when running Ansible 2.10+. Issue comes from aruba_module_installer.py installation script where Ansible max version is hard-coded and equals 2.9+

```
$ aruba-ansible-modules (master)> python aruba_module_installer/aruba_module_installer.py
There was an issue with your ansible version: 2.10.2
The Aruba Modules support Ansible release versions 2.5 or later.
```

**Comment by tchiapuziowong** [comment]
Hello @MauvaisJoueur !

**Comment by MauvaisJoueur** [comment]
Hello @tchiapuziowong 

I didn't know that Ansible Galaxy was superseding those modules. Does it mean I should close this issue and its associated pull request?
To answer your question, I'm just trying to automate management of standard modern Ethernet switches. Thing is I didn't manage to use the Ansible Galaxy collection you provide... I guess I'll have to try harder.

Best regards

**Comment by tchiapuziowong** [comment]
Looking at your pull request, it seems it just further enforces the versioning comparison. I can update the installer to make a note that 2.10 is not supported through this method of installation since at this time we're not going to update the installer to function with 2.10. If you have any questions on using the Ansible Galaxy content you can also post questions to our [Developer Community](https://community.arubanetworks.com/t5/Developer-Community/bd-p/DeveloperCommunity)

**Comment by MauvaisJoueur** [comment]
That's fine. Thank you very much.
