### ISSUE TITLE
arubaoss_interface.py

### ISSUE THREAD

**Issue by fallenfuzz** [aruba/aruba-ansible-modules#18]
option to remove interface description
option to have interface range (7,8 and 7-10 etc)

Thanks )

**Comment by hrv231** [comment]
+1 on this one.

**Comment by rajani-abraham** [comment]
As both are not supported in our REST APIs for AOS-Switch, Ansible modules also not supported. 

We have a module to use SSH instead of API. This module take all config commands supported using CLI.
https://github.com/aruba/aruba-switch-ansible/blob/master/library/arubaos_switch_ssh_cli.py 
Does that help you?

**Comment by fallenfuzz** [comment]
Followed https://community.arubanetworks.com/t5/Developer-Community/How-to-install-use-CLI-modules-and-tasks-for-Switch-and-CX-in/td-p/534333, cli config obviously works. Will use for missing stuff while Aruba team updates REST.

Thanks

**Comment by tchiapuziowong** [comment]
Hi @fallenfuzz due to the limitation of the REST API we're unable to allow ranges for interface configurations. But you are able to remove the description from an interface by supplying the module with an empty string "". I've updated the documentation to explain this behavior in commit f76f38b858666361994a9e1cbeaa8ece333eaaa5
