### ISSUE TITLE
port reference :: variable stack sizes

### ISSUE THREAD

**Issue by wazzfi** [aruba/aruba-ansible-modules#61]
how do we use Ansible to execute commands that will require a range of ports to be defined? especially across stacks with varying numbers. examples of config (colourless port config):

aaa authentication port-access eap-radius server-group "Mgmt_CPPM" aaa authentication mac-based chap-radius server-group "Mgmt_CPPM" aaa port-access gvrp-vlans aaa port-access authenticator 1/1-1/48,2/1-2/48 supplicant-timeout 10 aaa port-access authenticator 1/1-1/48,2/1-2/48 tx-period 10 aaa port-access authenticator 1/1-1/48,2/1-2/48 active aaa port-access 1/1-1/48,2/1-2/48 mixed

**Comment by tchiapuziowong** [comment]
Hi @wazzfi!! so I confirmed that port ranges aren't supported through REST API for any feature, we have to configure each port at a time, but with Ansible we can do that easily with [loops](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html) . We also have the SSH CLI module if you'd like to use that instead of the REST API module - [How to install/use CLI modules and tasks for Switch and CX in Ansible](https://community.arubanetworks.com/t5/Developer-Community/How-to-install-use-CLI-modules-and-tasks-for-Switch-and-CX-in/m-p/534333)

**Comment by tchiapuziowong** [comment]
closing issue
